config/routes.rb
Rails.application.routes.draw do
  resources :shopkeepers
  devise_for :admins
  get '/' => 'users#home'

  get 'users/about_us'

  get 'users/contact_us'

  get 'users/home'

  get 'users/join_us'

  post 'users/join_us_submit'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/repair.rb
class Repair < ActiveRecord::Base
  belongs_to :shopkeeper
end

app/models/shopkeeper.rb
class Shopkeeper < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/shopkeepers_controller.rb
class ShopkeepersController < ApplicationController
  before_filter :authenticate_admin!, only: :index
  before_action :set_shopkeeper, only: [:show, :edit, :update, :destroy]

  # GET /shopkeepers
  # GET /shopkeepers.json
  def index
    @shopkeepers = Shopkeeper.all
  end

  # GET /shopkeepers/1
  # GET /shopkeepers/1.json
  def show
  end

  # GET /shopkeepers/new
  def new
    @shopkeeper = Shopkeeper.new
  end

  # GET /shopkeepers/1/edit
  def edit
  end

  # POST /shopkeepers
  # POST /shopkeepers.json
  def create
    @shopkeeper = Shopkeeper.new(shopkeeper_params)

    respond_to do |format|
      if @shopkeeper.save
        format.html { redirect_to @shopkeeper, notice: 'Shopkeeper was successfully created.' }
        format.json { render :show, status: :created, location: @shopkeeper }
      else
        format.html { render :new }
        format.json { render json: @shopkeeper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shopkeepers/1
  # PATCH/PUT /shopkeepers/1.json
  def update
    respond_to do |format|
      if @shopkeeper.update(shopkeeper_params)
        format.html { redirect_to @shopkeeper, notice: 'Shopkeeper was successfully updated.' }
        format.json { render :show, status: :ok, location: @shopkeeper }
      else
        format.html { render :edit }
        format.json { render json: @shopkeeper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shopkeepers/1
  # DELETE /shopkeepers/1.json
  def destroy
    @shopkeeper.destroy
    respond_to do |format|
      format.html { redirect_to shopkeepers_url, notice: 'Shopkeeper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shopkeeper
      @shopkeeper = Shopkeeper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shopkeeper_params
      params.require(:shopkeeper).permit(:shopName, :ownerName, :address, :contact, :tv, :laptop, :washingMachine, :refrigerator, :geyser, :ac, :lights, :invertor, :houseWiring)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def about_us
  end

  def contact_us
  end

  def home
  end

  def join_us
  end

  def join_us_submit
  	verificationCodeForFormSubmission = "Qtaskers@123"
  	if (params["verification_code"] == verificationCodeForFormSubmission)
	  	shopName = params["shop_name"]
	  	address = params["address"]
	  	ownerName = params["owner_name"]
	  	contact = params["phone_number"]
	  	shopkeeper = Shopkeeper.where(contact: contact).first
	  	if (shopkeeper || shopName == "" || ownerName == "" || address == "" || contact == "")
	  		return redirect_to '/'
	  	else
	  		shopkeeper = Shopkeeper.new
	  		shopkeeper.shopName = shopName
	  		shopkeeper.ownerName = ownerName
	  		shopkeeper.address = address
      	shopkeeper.contact = contact
	  		if(params["tvRepair"] == "on")
	  			shopkeeper.tv = true
				else
					shopkeeper.tv = false
				end
		  		if(params["laptopRepair"] == "on")
		  			shopkeeper.laptop = true
		  		else
					shopkeeper.laptop = false
				end
		  		if(params["washingMachineRepair"] == "on")
		  			shopkeeper.washingMachine = true
		  		else
					shopkeeper.washingMachine = false
				end
		  		if(params["refrigeratorRepair"] == "on")
		  			shopkeeper.refrigerator = true
		  		else
					shopkeeper.refrigerator = false
				end
		  		if(params["geyserRepair"] == "on")
		  			shopkeeper.geyser = true
		  		else
					shopkeeper.geyser = false
				end
		  		if(params["acRepair"] == "on")
		  			shopkeeper.ac = true
		  		else
					shopkeeper.ac = false
				end
		  		if(params["lightsRepair"] == "on")
		  			shopkeeper.lights = true
		  		else
					shopkeeper.lights = false
				end
		  		if(params["invertorRepair"] == "on")
		  			shopkeeper.invertor = true
		  		else
					shopkeeper.invertor = false
				end
				if(params["houseWiringRepair"] == "on")
		  			shopkeeper.houseWiring = true
		  		else
					shopkeeper.houseWiring = false
				end
				shopkeeper.save
		  		return redirect_to '/'
		  	end
	  	else
	  		return redirect_to '/'
  	end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shopkeepers_helper.rb
module ShopkeepersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Qtaskers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body>
	
	<p class="notice"><%= notice %></p>
   	<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/layouts/index3.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by TEMPLATED
http://templated.co
Released for free under the Creative Commons Attribution License

Name       : MetroBiz 
Description: A two-column, fixed-width design with dark color scheme.
Version    : 1.0
Released   : 20140207

-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title></title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900" rel="stylesheet" />
<link href="default.css" rel="stylesheet" type="text/css" media="all" />
<link href="fonts.css" rel="stylesheet" type="text/css" media="all" />

<!--[if IE 6]><link href="default_ie6.css" rel="stylesheet" type="text/css" /><![endif]-->

</head>
<body>
<div id="header-wrapper">
	<div id="header" class="container">
		
		<div id="menu">
			<ul>
				<li class=""><a href="home.html.erb" accesskey="1" title="">Homepage</a></li>
				<li><a href="about_us.html.erb" accesskey="2" title="">About Us</a></li>
				
				<li><a href="join_us.html.erb" accesskey="4" title="">Join Us</a></li>
				<li><a href="conta_us.html.erb" accesskey="5" title="">Contact Us</a></li>
			</ul>
		</div>
	</div>
</div>


<div id="wrapper3">
<span id="career">
	<div id="welcome" class="container">
		<div class="title">
		
			<h2>Partnership Form</h2>
		</div>
		
		
<h2>Skill(s) required</h2>: Basic knowledge of Internet, MS-Excel, English Proficiency (Spoken), English Proficiency (Written), Hindi Proficiency (Spoken), good communication skills.
Who can apply:
Only those candidates can apply who:
1.	are residents of Delhi NCR region or Kanpur city (Uttar Pradesh).
2.	are available for duration of 3 months (mandatory) from the day of start of their internship.
3.	are pursuing any degree but have relevant skills and interest.
4.	are currently in any year of study.
Selected intern's day-to-day responsibilities include:  
1)	Field visits to increase the number of service providers linked with us.
2)	Interact with business owners, manage their work online and direct them through the processes.
3)	Interact with top level management.
Perks: Certificate, Letter of recommendation, Informal dress code, Free snacks & beverages during the field work, incentives on every increase in number of service provider.
*This is a work from home internship and interested candidates will be selected after a telephonic interview. Fill in the form given below and we will contact you as soon as possible.

Form (link)</br>
<!-- START Section - Reservations -->
  <section id="vam-career" class="section-container"> 
    
    <!-- START Section Heading -->
    <div class="wow fadeInDown" data-wow-duration="2s" data-wow-offset="250">
      <header class="section-heading">
        <h2 class="section-heading-title">Form</h2>
      </header>
    </div>
    <!-- END Section Heading -->
    
    <div class="grid-container">
      <div class="prefix-10 grid-80 suffix-10 tablet-grid-100 mobile-grid-100">
      <div class="grid-100"> 
          <!-- START Reservation Form -->
          <form id="vam-reservation-form" action="" method="post">
            <fieldset>
              <div class="grid-50 tablet-grid-50 mobile-grid-100"> 
                
                <!-- Name Field -->
                <p>
                  <label for="name">Name <span>*</span></label>
                  <input type="text" name="name" id="name" value="" required>
                </p>
                
                <!-- Email Field -->
                <p>
                  <label for="address">Address<span>*</span></label>
                  <input type="email" name="address" id="address" value="" required>
                </p>
                <p>
                  <label for="res_phone">Phone Number<span>*</span></label>
                  <input type="tel" name="res_phone" id="res_phone" value="" required>
                </p>
                
                <!-- Phone Number Field --> 
                
              
              </div>
              <div class="grid-50 tablet-grid-50 mobile-grid-100"> 
                
                <!-- Date Field -->
                <p>
                  <label for="subject">College<span>*</span></label>
                  <input type="text" name="subject" id="subject" value="" required>
                </p>
                <p>
                  <label for="res_email">Email<span>*</span></label>
                  <input type="email" name="res_email" id="res_email" value="" required>
                </p>
                <p>
                  <label for="res_mobile">Upload Your Resume<span>*</span></label>
                  
                  <input type="file" name="res_mobile" id="res_mobile" value="" style="clear:both; width:100%; border-radius:5px;" required>
             </p>
              
              </div>
              
            </fieldset>
          </form>
        </div>
        <!-- END Reservation Form --> 
        
        <!-- Form outcome contents. Generated through Ajax -->
        <div id="vam-reservation-form-outcome"></div>
      </div>
    </div>
  </section>
  <!-- END Section - Reservations --> </p>
  
  
  
    

</span>
	</div>
</div>
</body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Qtaskers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title></title>


  <!-- BOOTSTRAP -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

  <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900" rel="stylesheet" />
  <link href="fonts.css" rel="stylesheet" type="text/css" media="all" />
  <%= stylesheet_link_tag "default.css" %>
  <!--[if IE 6]><link href="default_ie6.css" rel="stylesheet" type="text/css" /><![endif]-->
  
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shopkeepers/_form.html.erb
<%= form_for(@shopkeeper) do |f| %>
  <% if @shopkeeper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shopkeeper.errors.count, "error") %> prohibited this shopkeeper from being saved:</h2>

      <ul>
      <% @shopkeeper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :shopName %><br>
    <%= f.text_field :shopName %>
  </div>
  <div class="field">
    <%= f.label :ownerName %><br>
    <%= f.text_field :ownerName %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :contact %><br>
    <%= f.text_field :contact %>
  </div>
  <div class="field">
    <%= f.label :tv %><br>
    <%= f.check_box :tv %>
  </div>
  <div class="field">
    <%= f.label :laptop %><br>
    <%= f.check_box :laptop %>
  </div>
  <div class="field">
    <%= f.label :washingMachine %><br>
    <%= f.check_box :washingMachine %>
  </div>
  <div class="field">
    <%= f.label :refrigerator %><br>
    <%= f.check_box :refrigerator %>
  </div>
  <div class="field">
    <%= f.label :geyser %><br>
    <%= f.check_box :geyser %>
  </div>
  <div class="field">
    <%= f.label :ac %><br>
    <%= f.check_box :ac %>
  </div>
  <div class="field">
    <%= f.label :lights %><br>
    <%= f.check_box :lights %>
  </div>
  <div class="field">
    <%= f.label :invertor %><br>
    <%= f.check_box :invertor %>
  </div>
  <div class="field">
    <%= f.label :houseWiring %><br>
    <%= f.check_box :houseWiring %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shopkeepers/edit.html.erb
<h1>Editing Shopkeeper</h1>

<%= render 'form' %>

<%= link_to 'Show', @shopkeeper %> |
<%= link_to 'Back', shopkeepers_path %>

app/views/shopkeepers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shopkeepers</h1>

<table>
  <thead>
    <tr>
      <th>S. No.
      <th>Shopname</th>
      <th>Ownername</th>
      <th>Address</th>
      <th>Contact</th>
      <th>Tv</th>
      <th>Laptop</th>
      <th>Washingmachine</th>
      <th>Refrigerator</th>
      <th>Geyser</th>
      <th>Ac</th>
      <th>Lights</th>
      <th>Invertor</th>
      <th>Housewiring</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% count = 0 %>
    <% @shopkeepers.each do |shopkeeper| %>
      <tr>
        <td><%= count = count + 1 %></td>
        <td><%= shopkeeper.shopName %></td>
        <td><%= shopkeeper.ownerName %></td>
        <td><%= shopkeeper.address %></td>
        <td><%= shopkeeper.contact %></td>
        <td><%= shopkeeper.tv %></td>
        <td><%= shopkeeper.laptop %></td>
        <td><%= shopkeeper.washingMachine %></td>
        <td><%= shopkeeper.refrigerator %></td>
        <td><%= shopkeeper.geyser %></td>
        <td><%= shopkeeper.ac %></td>
        <td><%= shopkeeper.lights %></td>
        <td><%= shopkeeper.invertor %></td>
        <td><%= shopkeeper.houseWiring %></td>
        <td><%= link_to 'Show', shopkeeper %></td>
        <td><%= link_to 'Edit', edit_shopkeeper_path(shopkeeper) %></td>
        <td><%= link_to 'Destroy', shopkeeper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shopkeeper', new_shopkeeper_path %>

app/views/shopkeepers/new.html.erb
<h1>New Shopkeeper</h1>

<%= render 'form' %>

<%= link_to 'Back', shopkeepers_path %>

app/views/shopkeepers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shopname:</strong>
  <%= @shopkeeper.shopName %>
</p>

<p>
  <strong>Ownername:</strong>
  <%= @shopkeeper.ownerName %>
</p>

<p>
  <strong>Address:</strong>
  <%= @shopkeeper.address %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @shopkeeper.contact %>
</p>

<p>
  <strong>Tv:</strong>
  <%= @shopkeeper.tv %>
</p>

<p>
  <strong>Laptop:</strong>
  <%= @shopkeeper.laptop %>
</p>

<p>
  <strong>Washingmachine:</strong>
  <%= @shopkeeper.washingMachine %>
</p>

<p>
  <strong>Refrigerator:</strong>
  <%= @shopkeeper.refrigerator %>
</p>

<p>
  <strong>Geyser:</strong>
  <%= @shopkeeper.geyser %>
</p>

<p>
  <strong>Ac:</strong>
  <%= @shopkeeper.ac %>
</p>

<p>
  <strong>Lights:</strong>
  <%= @shopkeeper.lights %>
</p>

<p>
  <strong>Invertor:</strong>
  <%= @shopkeeper.invertor %>
</p>

<p>
  <strong>Housewiring:</strong>
  <%= @shopkeeper.houseWiring %>
</p>

<%= link_to 'Edit', edit_shopkeeper_path(@shopkeeper) %> |
<%= link_to 'Back', shopkeepers_path %>

app/views/users/about_us.html.erb
<div id="header-wrapper">
	<div id="header" class="container">
		
		<div id="menu">
			<ul>
				<li class=""><a href="/users/home">Homepage</a></li>
				<li><a href="/users/about_us">About Us</a></li>
				
				<li><a href="/users/join_us">Join Us</a></li>
				<li><a href="/users/contact_us">Contact Us</a></li>
			</ul>
		</div>
	</div>
</div>

<div id="wrapper2">
<span id="aboutus">
	<div id="welcome" class="container">
		<div class="title">
		
			<h2>About Us</h2>
		</div>
		
		<p>Q Taskers is one of the fastest growing early stage start-up in India right now. We are solving a huge problem helping customers discover, vet and buy trusted local services on the internet. We are an internet marketplace for local services. As of now our services are limited only to electricians. With our promotion strategies founded on in-depth knowledge of regional markets, we provide the right professionals according to our client's needs. Our service providers are professionals who are at the top of their fields and immersed in local culture from your city. 
		What really sets us apart is our ability to solve the security issues. We hire only trusted and verified service providers as professionals and they happen to be from your own locality. We provide on-time services (every service provider will be at your door-step within an hour from booking otherwise free visit from our side is granted). We accept all basic methods of payment. These are the things which differentiate us from the others and make us perfectly suitable for the Indian market.
		We are staffed with young, passionate people working tirelessly to make a difference in the lives of people by catering to their service needs at their doorsteps. Be a part of our mission and give us a chance to serve you once. 
</p></span>
	</div>
</div>

app/views/users/contact_us.html.erb
<div id="header-wrapper">
  <div id="header" class="container">
    <div id="menu">
      <ul>
        <li class=""><a href="/users/home">Homepage</a></li>
        <li><a href="/users/about_us">About Us</a></li>
        <li><a href="/users/join_us">Join Us</a></li>
        <li><a href="/users/contact_us">Contact Us</a></li>
      </ul>
    </div>
  </div>
</div>

<div id="wrapper2">
<span id="contact">
  <div id="footer" class="container">
  <div class="grid-container">
    <div class="prefix-10 grid-80 suffix-10 tablet-grid-100 mobile-grid-100">
      <div>
        <header class="title">
          <h2>Get in touch</h2>
        </header>
      </div>
      <h5 class="section-heading-title1">Feel free to contact us at the below address</h5>
      <div class="grid-40">
        <!--<img src="images/contact.png"/><br/><br/>-->
        <br><br>
        <address>
          <strong>Corporate Office Address</strong><br>
          <i class="fa fa-map-marker icons"></i>NIIT University, NH 8, Delhi- Jaipur Highway,<br>
          <span class="aside">Neemrana, Rajasthan 301705<br>
          </span>qtaskers@gmail.com
        </address>
        <div class="phn"><i class="fa fa-phone icons"></i>+91 9473503761</div>
        <div class="phn"><i class="fa fa-envelope-o icons"></i><a href="mailto:qtaskers@gmail.com" class="link-a">Contact@ Q-Taskers</a></div>
        </address>
      </div>
      <div class="grid-60"> 
      </div>
      <!-- END Reservation Form --> 
      <!-- contact -->
      <!-- copyright -->
      <div class="copyright-agile">
        <p>&copy; 2017 Qtaskers. All rights reserved</p>
      </div>
      <!-- //copyright -->
    </div>
  </div>
  <div>
    <ul class="contact">
      <li><a href="#" class="icon icon-twitter"><span>Twitter</span></a></li>
      <li><a href="#" class="icon icon-facebook"><span></span></a></li>
      <li><a href="#" class="icon icon-dribbble"><span>Pinterest</span></a></li>
      <li><a href="#" class="icon icon-tumblr"><span>Google+</span></a></li>
      <li><a href="#" class="icon icon-rss"><span>Pinterest</span></a></li>
    </ul>
  </div>
  <div id="copyright" class="container">
    <p>&copy; 2017 Q-Taskers. All rights reserved. | Call: +919473503761 | Mail: qtaskers@gmail.com</a>.</p>
</span>
</div>

app/views/users/home.html.erb
<div id="header-wrapper">
	<div id="header" class="container">
		<div id="logo">
			<h1><a href="#">Q-Taskers</a></h1>
			<span>is Coming Soon...</a></span>
		</div>
		<div id="menu">
			<ul>
				<li><a href="/users/home">Homepage</a></li>
				<li><a href="/users/about_us">About Us</a></li>
				
				<li><a href="/users/join_us">Join Us</a></li>
				<li><a href="/users/contact_us">Contact Us</a></li>
			</ul>
		</div>
	</div>
</div>

app/views/users/join_us.html.erb
<div id="header-wrapper">
	<div id="header" class="container">
		
		<div id="menu">
			<ul>
				<li class=""><a href="/users/home">Homepage</a></li>
        <li><a href="/users/about_us">About Us</a></li>
        
        <li><a href="/users/join_us">Join Us</a></li>
        <li><a href="/users/contact_us">Contact Us</a></li>
			</ul>
		</div>
	</div>
</div>


<div id="wrapper3">
  <span id="career">
  	<div id="welcome2" class="container">
  		<div class="title">
  			<h2>Partnership Form</h2>
  		</div>
      <section id="vam-career" class="section-container"> 
        <div class="grid-container">
          <div> 
            <form id="vam-reservation-form" class="form-horizontal" action="/users/join_us_submit" method="POST">
              <div class="form-group">
                <div>
                  <div class="form-group">
                    <label for="shop_name" class="col-sm-12 control-label">Shop Name*</label>
                    <div class="col-sm-10">
                      <input type="text" name="shop_name" id="name" class="form-control">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="owner_name" class="col-sm-12 control-label">Shop Owner Name*</label>
                    <div class="col-sm-10">
                      <input type="text" name="owner_name" id="name" class="form-control">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="address" class="col-sm-12 control-label">Address*</label>
                    <div class="col-sm-10">
                      <textarea type="text" name="address" id="address" class="form-control"></textarea>
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="phone_no" class="col-sm-12 control-label">Phone Number*</label>
                    <div class="col-sm-10">
                      <input type="tel" name="phone_number" id="res_phone" class="form-control">
                    </div>
                  </div>
                  <div style="text-align: left;">
                    <div class="checkbox">
                      <label>
                        <input type="checkbox" name="tvRepair"> TV/LCD/LED repair
                      </label>
                    </div>
                    <div class="checkbox">
                      <label>
                        <input type="checkbox" name="laptopRepair"> Laptop/PC repair
                      </label>
                    </div>
                    <div class="checkbox">
                      <label>
                        <input type="checkbox" name="washingMachineRepair"> Washing machine repair
                      </label>
                    </div>
                    <div class="checkbox">
                      <label>
                        <input type="checkbox" name="refrigeratorRepair"> Refrigerator repair
                      </label>
                    </div>
                    <div class="checkbox">
                      <label>
                        <input type="checkbox" name="geyserRepair"> Geyser/Water heater repair
                      </label>
                    </div>
                    <div class="checkbox">
                      <label>
                        <input type="checkbox" name="acRepair"> AC/Cooler/Fan repair
                      </label>
                    </div>
                    <div class="checkbox">
                      <label>
                        <input type="checkbox" name="lightsRepair"> Lights repair
                      </label>
                    </div>
                    <div class="checkbox">
                      <label>
                        <input type="checkbox" name="invertersRepair"> Inverters/Generators repair
                      </label>
                    </div>
                    <div class="checkbox">
                      <label>
                        <input type="checkbox" name="houseWiringRepair"> House wiring
                      </label>
                    </div>
                  </div>
                  <br>
                  <div class="form-group">
                    <label for="verification_code" class="col-sm-12 control-label">Verification Code* (Code given by the company with prior contact)</label>
                    <div class="col-sm-5">
                      <input type="text" name="verification_code" class="form-control">
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-sm-12">
                      <button type="submit" class="btn btn-primary">Submit</button>
                      <p>We will contact you as soon as possible</p>
                    </div>
                  </div>
                </div>  
              </div>   
            </form>
          </div>
        </div>
      </section>
    </div>
  </span>
</div>